name : Actions Workflow

on : [push]

jobs: 
  run-github-actions :
    runs-on : ubuntu-latest
    steps:
      - name : List files
        run : |
          pwd 
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github : udemyexamplenik/$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name : simple JS Actions
        id : greet
        uses : actions/hello-world-javascript-action@v1
        with:
          who-to-greet : John
      - name : Log Greeting Time
        run : echo "${{ steps.greet.outputs.time }}"
      - name : Check the checkout funciton
        uses : actions/checkout@v1
      - name : Check the execution folder after checkout
        run : |
          pwd 
          ls -al
        
      
        