name : Actions Workflow

on : [push]

jobs: 
  run-github-actions :
    runs-on : ubuntu-latest
    steps:
      - name : Check the execution folder
        run : |
          pwd 
          ls -al
      - name : simple JS Actions
        id : greet
        uses : actions/hello-world-javascript-action@v1
        with:
          who-to-greet : John
      - name : Log Greeting Time
        run : echo "${{ steps.greet.outputs.time }}"
      - name : Check the checkout funciton
        uses : action/checkout@v1
      - name : Check the execution folder after checkout
        run : |
          pwd 
          ls -al
        
      
        