name : Test shell commands

on : [push]

jobs : 
  run-shell-command : 
    runs-on : ubuntu-latest
    steps : 
      - name : Echo a string
        run : echo "Hello World"
      - name : multiline script
        run : |
          node -v
          npm -v
  python-command :
    runs-on : ubuntu-latest
    steps:
      - name : python commands
        run : |
          import platform
          print(platform.processor())
        shell : python
  using-bash-on-windows : 
    runs-on : windows-latest
    needs : 
      - run-shell-command
    steps : 
      - name : Directory PowerShell
        run : Get-Location
      - name : Directory bash
        run : pwd
        shell: bash
  
